import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from '../components/SideBar/SideBar'
import TopBar from '../components/TopBar/TopBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
 {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-screen'>
          <div className='h-full mx-auto'>
            <div className='h-full flex flex-row'>
              <SideBar />
              <div className='flex flex-col flex-1 bg-[#F8F8FF]'>
                <TopBar />
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}